name: release
on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ".gz"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release

      - name: Compress and rename executable
        if: ${{ matrix.os != 'windows-latest' }}
        run: gzip -c target/${{ matrix.target }}/release/svd2html > svd2html-${{ matrix.target }}${{ matrix.suffix }}
      - name: Rename executable
        if: ${{ matrix.os == 'windows-latest' }}
        run: mv target/${{ matrix.target }}/release/svd2html${{ matrix.suffix }} svd2html-${{ matrix.target }}${{ matrix.suffix }}

      - uses: actions/upload-artifact@v3
        with:
          name: svd2html-${{ matrix.target }}
          path: svd2html-${{ matrix.target }}${{ matrix.suffix }}

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - run: ls -R ./artifacts

      - name: Set current date as environment variable
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - id: changelog-reader
        uses: mindsers/changelog-reader-action@v2.0.0
        with:
          version: ${{ (github.ref_type == 'tag' && github.ref_name) || 'Unreleased' }}

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.changelog-reader.outputs.version }}
          name: ${{ (github.ref_type == 'tag' && steps.changelog-reader.outputs.version) || format('Prereleased {0}', env.CURRENT_DATE) }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          prerelease: ${{ steps.changelog-reader.outputs.status == 'unreleased' }}
          files: |
            artifacts/**/*
